// Thin wrapper around the WASM module built from native/ + vendor/pcdtojpeg
// (see scripts/build-wasm.mjs). Speaks the module's file-in/file-out calling
// convention (Emscripten MEMFS) so callers just deal with byte arrays.

// @ts-expect-error - generated by scripts/build-wasm.mjs at build time; not present until then
import createPcdCodecModule from "../wasm/pcd-codec.mjs";

export type PcdFormat = "jpeg" | "tiff";
export type WhiteBalance = "D65" | "D50";

// Mirrors enum PCDResolutions in vendor/pcdtojpeg/src/pcdDecode.h
export const PCD_RESOLUTIONS = [
  { value: 0, label: "Base/16 — 128 × 192 (thumbnail)" },
  { value: 1, label: "Base/4 — 256 × 384 (web)" },
  { value: 2, label: "Base — 512 × 768 (screen)" },
  { value: 3, label: "4Base — 1024 × 1536 (HD)" },
  { value: 4, label: "16Base — 2048 × 3072 (print)" },
  { value: 5, label: "64Base — 4096 × 6144 (needs an Overview Pac file; falls back if unavailable)" },
] as const;

// 64Base is the highest resolution PhotoCD supports. A standalone .pcd file
// never actually carries 64Base data on its own (that needs a companion
// Overview Pac file this app doesn't ask for) - so this always falls back to
// the best resolution actually available in the file, reported as a warning
// rather than an error. Defaulting to it means every conversion always gets
// the maximum quality the source file can provide.
export const DEFAULT_RESOLUTION = 5;

export interface ConvertOptions {
  format: PcdFormat;
  resolution: number;
  whiteBalance: WhiteBalance;
  monochrome: boolean;
  jpegQuality: number; // 1-100, ignored for TIFF
}

export interface ConvertResult {
  data: Uint8Array;
  width: number;
  height: number;
  /** Non-fatal note from the decoder, e.g. "requested resolution unavailable, used 4Base instead". */
  warning: string | null;
}

interface PcdCodecModule {
  FS: {
    writeFile(path: string, data: Uint8Array): void;
    readFile(path: string, opts?: { encoding: "binary" }): Uint8Array;
    unlink(path: string): void;
  };
  ccall(
    name: string,
    returnType: string,
    argTypes: string[],
    args: (string | number)[]
  ): number;
  _malloc(size: number): number;
  _free(ptr: number): void;
  getValue(ptr: number, type: string): number;
  UTF8ToString(ptr: number): string;
}

let modulePromise: Promise<PcdCodecModule> | null = null;

function getModule(): Promise<PcdCodecModule> {
  if (!modulePromise) {
    modulePromise = createPcdCodecModule() as Promise<PcdCodecModule>;
  }
  return modulePromise;
}

/** Kicks off loading the (multi-hundred-KB) WASM module ahead of time. */
export function preloadPcdCodec(): Promise<unknown> {
  return getModule();
}

let callCounter = 0;

const FORMAT_CODES: Record<PcdFormat, number> = { jpeg: 0, tiff: 1 };
const WHITE_BALANCE_CODES: Record<WhiteBalance, number> = { D65: 0, D50: 1 };

export async function convertPcd(
  fileBytes: Uint8Array,
  options: ConvertOptions
): Promise<ConvertResult> {
  const Module = await getModule();

  const callId = callCounter++;
  const inPath = `/in-${callId}.pcd`;
  const outPath = options.format === "tiff" ? `/out-${callId}.tif` : `/out-${callId}.jpg`;

  const outWidthPtr = Module._malloc(4);
  const outHeightPtr = Module._malloc(4);
  const messageBufLen = 512;
  const messagePtr = Module._malloc(messageBufLen);

  try {
    Module.FS.writeFile(inPath, fileBytes);

    const rc = Module.ccall(
      "pcd_convert",
      "number",
      [
        "string",
        "string",
        "number",
        "number",
        "number",
        "number",
        "number",
        "number",
        "number",
        "number",
        "number",
      ],
      [
        inPath,
        outPath,
        FORMAT_CODES[options.format],
        options.resolution,
        WHITE_BALANCE_CODES[options.whiteBalance],
        options.monochrome ? 1 : 0,
        options.jpegQuality,
        outWidthPtr,
        outHeightPtr,
        messagePtr,
        messageBufLen,
      ]
    );

    const width = Module.getValue(outWidthPtr, "i32");
    const height = Module.getValue(outHeightPtr, "i32");
    const message = Module.UTF8ToString(messagePtr);

    if (rc !== 0) {
      throw new Error(message || `PCD conversion failed (error code ${rc})`);
    }

    const data = Module.FS.readFile(outPath, { encoding: "binary" });
    // Copy out of the module's MEMFS-backed buffer before we unlink/reuse it.
    return { data: new Uint8Array(data), width, height, warning: message || null };
  } finally {
    Module._free(outWidthPtr);
    Module._free(outHeightPtr);
    Module._free(messagePtr);
    try {
      Module.FS.unlink(inPath);
    } catch {
      /* not written, e.g. if writeFile itself threw */
    }
    try {
      Module.FS.unlink(outPath);
    } catch {
      /* not produced, e.g. decode failed before encoding */
    }
  }
}
